In [1]:
import numpy as np
a = np.array([1, 2, 3])
print('a =', a)
print('type(a) =', type(a))
print('a.dtype =', a.dtype)
print('a.ndim =', a.ndim)
print('a.size =', a.size)
print('a.shape =', a.shape)

b = np.array([[1.3, 2.4], [0.3, 4.1]])
print('b =', b)
print('type(b) =', type(b))
print('b.dtype =', b.dtype)
print('b.ndim =', b.ndim)
print('b.size =', b.size)
print('b.shape =', b.shape)


a = [1 2 3]
type(a) = <class 'numpy.ndarray'>
a.dtype = int32
a.ndim = 1
a.size = 3
a.shape = (3,)
b = [[1.3 2.4]
 [0.3 4.1]]
type(b) = <class 'numpy.ndarray'>
b.dtype = float64
b.ndim = 2
b.size = 4
b.shape = (2, 2)


In [2]:
import numpy as np;

g = np.array([['a', 'g'], ['c', 'd']])
print('g =', g)
print('type(g) =', type(g))
print('g.dtype =', g.dtype)
print('g.dtype.name =', g.dtype.name)
print('g.ndim =', g.ndim)
print('g.size =', g.size)
print('g.shape =', g.shape)


g = [['a' 'g']
 ['c' 'd']]
type(g) = <class 'numpy.ndarray'>
g.dtype = <U1
g.dtype.name = str32
g.ndim = 2
g.size = 4
g.shape = (2, 2)


In [3]:
import numpy as np

a = np.arange(4)
print(a)
print(a+4)
print(a*4)
print()

b = np.arange(4,8)
print(b)
print(a+b)
print(a-b)
print(a*b)
print()

A = np.arange(0,9).reshape(3,3)
print(A)
B = np.ones((3,3))
print(B)
print(A*B)
print(A-B)


[0 1 2 3]
[4 5 6 7]
[ 0  4  8 12]

[4 5 6 7]
[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [4]:
import numpy as np

A = np.arange(0,9).reshape(3,3)
print(A)
print()

B = np.ones((3,3))
print(B)
print()

print(np.dot(A,B))


[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [5]:
import numpy as np

a = np.arange(10,16)
print(a)
print(a[4])
print()

A = np.arange(10,19).reshape((3,3))
print(A)
print(A[0,0])
print(A[1,1])
print(A[2,2])


[10 11 12 13 14 15]
14

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10
14
18


In [6]:
import numpy as np

A = np.arange(10,19).reshape((3,3))
print(A)

for i in range(0,3):
    for j in range(0,3):
        print(A[i,j])

print()

for row in A:
    print(row)

print()

for row in A:
    for col in row:
        print(col)


[[10 11 12]
 [13 14 15]
 [16 17 18]]
10
11
12
13
14
15
16
17
18

[10 11 12]
[13 14 15]
[16 17 18]

10
11
12
13
14
15
16
17
18


In [7]:
#import numpy as np
import pandas as pd

s = pd.Series([12, -4, 7, 9])
print(s)


0    12
1    -4
2     7
3     9
dtype: int64


In [8]:
import numpy as np
import pandas as pd

s = pd.Series([12, -4, 7, 9], index=['a', 'b', 'c', 'd'])
print(s)
print()

# Selecting elements
print(s[2])
print(s['b'])
print(s[0:2])
print(s[['b','c']])
print()

# Assignment
s[1] = 0
print(s)
print()

s['b'] = 1
print(s)
print()

# Filtering values
print(s[s>8])
print()

#Operations and math functions
print(s/2)
print()

print(np.log(s))
print()



a    12
b    -4
c     7
d     9
dtype: int64

7
-4
a    12
b    -4
dtype: int64
b   -4
c    7
dtype: int64

a    12
b     0
c     7
d     9
dtype: int64

a    12
b     1
c     7
d     9
dtype: int64

a    12
d     9
dtype: int64

a    6.0
b    0.5
c    3.5
d    4.5
dtype: float64

a    2.484907
b    0.000000
c    1.945910
d    2.197225
dtype: float64



In [9]:
import numpy as np
import pandas as pd

serd = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])
print(serd)
print()

# All unique values without duplicates
print(serd.unique())
print()

# Return unique values with counting of occurences
print(serd.value_counts())
print()

# Evaluates values membership
print(serd.isin([0,3]))
print()
print(serd[serd.isin([0,3])])


white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

[1 0 2 3]

2    2
1    2
3    1
0    1
dtype: int64

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool

white     0
yellow    3
dtype: int64


In [10]:
import numpy as np
import pandas as pd

mydict1 = {'red':2000, 'blue': 1000, 'yellow':500, 'orange':1000}
myseries1 = pd.Series(mydict1)
print(myseries1)
print()

mydict2 = {'red':400, 'yellow':1000, 'black':700}
myseries2 = pd.Series(mydict2)
print(myseries2)
print()

myseries3 = myseries1 + myseries2
print(myseries3)


red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

red        400
yellow    1000
black      700
dtype: int64

black        NaN
blue         NaN
orange       NaN
red       2400.0
yellow    1500.0
dtype: float64


In [13]:
import numpy as np
import pandas as pd

data = {'color': ['blue','green','yellow','red','white'],
        'object': ['ball','pen','pencil','paper','mug'],
        'price':[1.2,1.0,0.6,0.9,1.7]}

print(data)
print()

frame = pd.DataFrame(data)
print(frame)

print(frame.loc[1])

{'color': ['blue', 'green', 'yellow', 'red', 'white'], 'object': ['ball', 'pen', 'pencil', 'paper', 'mug'], 'price': [1.2, 1.0, 0.6, 0.9, 1.7]}

    color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7
color     green
object      pen
price         1
Name: 1, dtype: object


In [15]:
import numpy as np
import pandas as pd

data = {'color': ['blue','green','yellow','red','white'],
        'object': ['ball','pen','pencil','paper','mug'],
        'price':[1.2,1.0,0.6,0.9,1.7]}

frame = pd.DataFrame(data)

print(frame.columns)
print()
print(frame.index)
print()
print(frame.values)
print()

print(frame['price'])
print()
print(frame.price)
print()
print(frame.loc[0])
print()
print(frame.loc[0]['price'])
print()
print(frame.loc[0].price)
print()


Index(['color', 'object', 'price'], dtype='object')

RangeIndex(start=0, stop=5, step=1)

[['blue' 'ball' 1.2]
 ['green' 'pen' 1.0]
 ['yellow' 'pencil' 0.6]
 ['red' 'paper' 0.9]
 ['white' 'mug' 1.7]]

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

color     blue
object    ball
price      1.2
Name: 0, dtype: object

1.2

1.2



In [16]:
import numpy as np
import pandas as pd

data = {'color': ['blue','green','yellow','red','white'],
        'object': ['ball','pen','pencil','paper','mug'],
        'price':[1.2,1.0,0.6,0.9,1.7]}

frame = pd.DataFrame(data)

print(frame.price)

for i in range(0, len(frame.index)):
    frame.loc[i,'price'] = 8.88

print(frame.price)
print()

frame.loc[2,'price'] = 9.99
print(frame.price)


0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64
0    8.88
1    8.88
2    8.88
3    8.88
4    8.88
Name: price, dtype: float64

0    8.88
1    8.88
2    9.99
3    8.88
4    8.88
Name: price, dtype: float64


In [17]:
import numpy as np
import pandas as pd

data1 = {'ball': [0,4,8,12],
        'pen': [1,5,9,13],
        'pencil': [2,6,10,14],
        'paper':[3,7,11,15]}

frame1 = pd.DataFrame(data1, index=['red','blue','yellow','white'])

print(frame1)
print()

data2 = {'mug': [0,3,6,9],
        'pen': [1,4,7,10],
        'ball': [2,5,8,11]}

frame2 = pd.DataFrame(data2, index=['blue','green','white','yellow'])

print(frame2)
print()

frame3 = frame1.add(frame2)
print(frame3)


        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

        mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

        ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN


In [18]:
import numpy as np
import pandas as pd

data1 = {'ball': [0,4,8,12],
        'pen': [1,5,9,13],
        'pencil': [2,6,10,14],
        'paper':[3,7,11,15]}

frame1 = pd.DataFrame(data1, index=['red','blue','yellow','white'])

print(frame1.sum())
print()
print(frame1.mean())
print()
print(frame1.describe())


ball      24
pen       28
pencil    32
paper     36
dtype: int64

ball      6.0
pen       7.0
pencil    8.0
paper     9.0
dtype: float64

            ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000
